# Generated by Django 6.0.7 on 2026-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Python', help_text='Example: Python, Django, SQLite', max_length=255),
        ),
    ]
