# Generated by Django 6.0.7 on 2026-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Learning', max_length=30),
        ),
    ]
